Repository googleapis/nodejs-talent, pull requests merged in 2019-05, with the labels that each got.

#42 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#41 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#43 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#46 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#47 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#45 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#49 feat: add Resume and keywordSearchableProfileCustomAttributes
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/google/cloud/talent/v4beta1/application.proto
  protos/google/cloud/talent/v4beta1/common.proto
  protos/google/cloud/talent/v4beta1/filters.proto
  protos/google/cloud/talent/v4beta1/job.proto
  protos/google/cloud/talent/v4beta1/profile.proto
  protos/google/cloud/talent/v4beta1/profile_service.proto
  protos/google/cloud/talent/v4beta1/tenant.proto
  src/v4beta1/application_service_client_config.json
  src/v4beta1/company_service_client_config.json
  src/v4beta1/completion_client_config.json
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_application.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_common.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_filters.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_tenant.js
  src/v4beta1/event_service_client_config.json
  src/v4beta1/job_service_client_config.json
  src/v4beta1/profile_service_client.js
  src/v4beta1/profile_service_client_config.json
  src/v4beta1/tenant_service_client_config.json
  synth.metadata
  test/gapic-v4beta1.js
Labels: cla: yes

#50 chore: release 0.3.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#52 fix: DEADLINE_EXCEEDED is idempotent
  src/v4beta1/application_service_client_config.json
  src/v4beta1/company_service_client_config.json
  src/v4beta1/completion_client_config.json
  src/v4beta1/event_service_client_config.json
  src/v4beta1/job_service_client_config.json
  src/v4beta1/profile_service_client_config.json
  src/v4beta1/tenant_service_client_config.json
  synth.metadata
Labels: cla: yes

#53 chore: use repo-metadata to generate readme
  .cloud-repo-tools.json
  .repo-metadata.json
  README.md
  package.json
  synth.metadata
Labels: cla: yes

#54 fix: use SummarizedProfile over HistogramQueryResult
  src/v4beta1/profile_service_client.js
  synth.metadata
  test/gapic-v4beta1.js
Labels: cla: yes

#55 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#59 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#61 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v4beta1/application_service_client.js
  src/v4beta1/company_service_client.js
  src/v4beta1/completion_client.js
  src/v4beta1/event_service_client.js
  src/v4beta1/job_service_client.js
  src/v4beta1/profile_service_client.js
  src/v4beta1/tenant_service_client.js
  synth.metadata
Labels: cla: yes

#62 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#63 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#64 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#66 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
