Repository googleapis/nodejs-talent, pull requests merged in 2019-06, with the labels that each got.

#67 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#68 chore: release 1.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#71 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#72 chore: release 1.0.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#73 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes

#69 feat: batch operation support
  .eslintrc.yml
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  protos/google/cloud/talent/v4beta1/application.proto
  protos/google/cloud/talent/v4beta1/batch.proto
  protos/google/cloud/talent/v4beta1/common.proto
  protos/google/cloud/talent/v4beta1/company.proto
  protos/google/cloud/talent/v4beta1/completion_service.proto
  protos/google/cloud/talent/v4beta1/event.proto
  protos/google/cloud/talent/v4beta1/filters.proto
  protos/google/cloud/talent/v4beta1/histogram.proto
  protos/google/cloud/talent/v4beta1/job.proto
  protos/google/cloud/talent/v4beta1/job_service.proto
  protos/google/cloud/talent/v4beta1/profile.proto
  protos/google/cloud/talent/v4beta1/profile_service.proto
  src/index.js
  src/v4beta1/application_service_client.js
  src/v4beta1/company_service_client.js
  src/v4beta1/completion_client.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_common.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_company.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_completion_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_event.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_filters.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_histogram.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_job.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_job_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile_service.js
  src/v4beta1/doc/google/longrunning/doc_operations.js
  src/v4beta1/doc/google/protobuf/doc_any.js
  src/v4beta1/doc/google/rpc/doc_status.js
  src/v4beta1/doc/google/type/doc_postal_address.js
  src/v4beta1/event_service_client.js
  src/v4beta1/job_service_client.js
  src/v4beta1/job_service_client_config.json
  src/v4beta1/profile_service_client.js
  src/v4beta1/tenant_service_client.js
  synth.metadata
  synth.py
  test/gapic-v4beta1.js
Labels: :rotating_light:, cla: yes, priority: p1

#74 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process
