Repository googleapis/nodejs-talent, pull requests merged in 2019-04, with the labels that each got.

#31 feat: add templates for company old path
  src/v4beta1/completion_client.js
  src/v4beta1/job_service_client.js
  synth.metadata
Labels: cla: yes

#32 refactor: use execSync for tests
  samples/package.json
Labels: automerge, cla: yes

#36 docs: update formatting of jsdoc annotations
  protos/google/cloud/talent/v4beta1/application.proto
  protos/google/cloud/talent/v4beta1/application_service.proto
  protos/google/cloud/talent/v4beta1/common.proto
  protos/google/cloud/talent/v4beta1/company.proto
  protos/google/cloud/talent/v4beta1/company_service.proto
  protos/google/cloud/talent/v4beta1/completion_service.proto
  protos/google/cloud/talent/v4beta1/event.proto
  protos/google/cloud/talent/v4beta1/filters.proto
  protos/google/cloud/talent/v4beta1/histogram.proto
  protos/google/cloud/talent/v4beta1/job.proto
  protos/google/cloud/talent/v4beta1/job_service.proto
  protos/google/cloud/talent/v4beta1/profile.proto
  protos/google/cloud/talent/v4beta1/profile_service.proto
  protos/google/cloud/talent/v4beta1/tenant.proto
  protos/google/cloud/talent/v4beta1/tenant_service.proto
  src/v4beta1/application_service_client.js
  src/v4beta1/company_service_client.js
  src/v4beta1/completion_client.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_application.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_application_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_common.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_company.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_company_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_completion_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_event.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_filters.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_histogram.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_job.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_job_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_tenant.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_tenant_service.js
  src/v4beta1/job_service_client.js
  src/v4beta1/profile_service_client.js
  src/v4beta1/tenant_service_client.js
  synth.metadata
Labels: :rotating_light:, cla: yes

#39 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes

#38 refactor: update formatting of generated code
  src/v4beta1/application_service_client.js
  src/v4beta1/company_service_client.js
  src/v4beta1/completion_client.js
  src/v4beta1/doc/google/protobuf/doc_field_mask.js
  src/v4beta1/doc/google/protobuf/doc_timestamp.js
  src/v4beta1/job_service_client.js
  src/v4beta1/profile_service_client.js
  synth.metadata
  test/gapic-v4beta1.js
Labels: cla: yes
