Repository googleapis/nodejs-talent, pull requests merged in 2019-09, with the labels that each got.

#93 feat: load protos from JSON, grpc-fallback support
  protos/protos.json
  src/browser.js
  src/service_proto_list.json
  src/v4beta1/application_service_client.js
  src/v4beta1/application_service_proto_list.json
  src/v4beta1/company_service_client.js
  src/v4beta1/company_service_proto_list.json
  src/v4beta1/completion_client.js
  src/v4beta1/completion_proto_list.json
  src/v4beta1/event_service_client.js
  src/v4beta1/event_service_proto_list.json
  src/v4beta1/job_service_client.js
  src/v4beta1/job_service_proto_list.json
  src/v4beta1/profile_service_client.js
  src/v4beta1/profile_service_proto_list.json
  src/v4beta1/tenant_service_client.js
  src/v4beta1/tenant_service_proto_list.json
  synth.metadata
  test/gapic-v4beta1.js
  webpack.config.js
Labels: cla: yes

#96 chore: remove conformance tests from .nycrc
  .nycrc
Labels: cla: yes

#97 feat: filter support
  protos/google/cloud/talent/v4beta1/application.proto
  protos/google/cloud/talent/v4beta1/application_service.proto
  protos/google/cloud/talent/v4beta1/batch.proto
  protos/google/cloud/talent/v4beta1/common.proto
  protos/google/cloud/talent/v4beta1/company.proto
  protos/google/cloud/talent/v4beta1/company_service.proto
  protos/google/cloud/talent/v4beta1/completion_service.proto
  protos/google/cloud/talent/v4beta1/event.proto
  protos/google/cloud/talent/v4beta1/event_service.proto
  protos/google/cloud/talent/v4beta1/filters.proto
  protos/google/cloud/talent/v4beta1/histogram.proto
  protos/google/cloud/talent/v4beta1/job.proto
  protos/google/cloud/talent/v4beta1/job_service.proto
  protos/google/cloud/talent/v4beta1/profile.proto
  protos/google/cloud/talent/v4beta1/profile_service.proto
  protos/google/cloud/talent/v4beta1/tenant.proto
  protos/google/cloud/talent/v4beta1/tenant_service.proto
  protos/protos.json
  src/v4beta1/application_service_client.js
  src/v4beta1/company_service_client.js
  src/v4beta1/completion_client.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_application.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_application_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_common.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_company.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_company_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_completion_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_event.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_event_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_filters.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_histogram.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_job.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_job_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile_service.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_tenant.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_tenant_service.js
  src/v4beta1/event_service_client.js
  src/v4beta1/job_service_client.js
  src/v4beta1/profile_service_client.js
  src/v4beta1/tenant_service_client.js
  synth.metadata
Labels: cla: yes

#98 feat: candidate applications and assignments support
  protos/google/cloud/talent/v4beta1/profile.proto
  protos/protos.json
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile.js
  synth.metadata
Labels: cla: yes, kokoro:force-run

#94 chore: release 1.4.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#99 build: switch to GitHub app for releases
  .github/release-please.yml
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
Labels: cla: yes

#101 feat: .d.ts for protos
  protos/google/cloud/talent/v4beta1/common.proto
  protos/google/cloud/talent/v4beta1/filters.proto
  protos/google/cloud/talent/v4beta1/profile.proto
  protos/google/cloud/talent/v4beta1/profile_service.proto
  protos/protos.json
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_common.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_filters.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile.js
  src/v4beta1/doc/google/cloud/talent/v4beta1/doc_profile_service.js
  src/v4beta1/profile_service_client.js
  synth.metadata
Labels: cla: yes

#103 chore: add protos/ to .eslintignore
  .eslintignore
Labels: cla: yes

#104 feat: .d.ts for protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes

#105 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes
