Repository googleapis/nodejs-talent, pull requests merged in 2020-07, with the labels that each got.

#212 docs: Remove a broken link from the documentation.
  protos/google/cloud/talent/v4beta1/filters.proto
  synth.metadata
Labels: cla: yes, context: full, context: partial

#219 build: use bazel build
  src/v4beta1/company_service_client.ts
  src/v4beta1/completion_client.ts
  src/v4beta1/event_service_client.ts
  src/v4beta1/job_service_client.ts
  src/v4beta1/profile_service_client.ts
  src/v4beta1/tenant_service_client.ts
  synth.metadata
  synth.py
  test/gapic_company_service_v4beta1.ts
  test/gapic_completion_v4beta1.ts
  test/gapic_event_service_v4beta1.ts
  test/gapic_job_service_v4beta1.ts
  test/gapic_profile_service_v4beta1.ts
  test/gapic_tenant_service_v4beta1.ts
Labels: automerge, cla: yes

#220 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#223 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#225 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#227 build: type in .gittatribute, missing closing paren in publish script, delete template for Node 8 tests, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: partial

#226 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#228 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#229 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#230 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#232 build: config for new reference docs
  .kokoro/release/docs-devsite.cfg
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial
