Repository googleapis/nodejs-talent, pull requests merged in 2020-11, with the labels that each got.

#262 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: full

#263 build: add v4.CompanyServiceClient type
  src/index.ts
  synth.metadata
Labels: api: jobs, cla: yes, context: none

#264 fix: do not modify options object, use defaultScopes
  package.json
  src/v4/company_service_client.ts
  src/v4/completion_client.ts
  src/v4/event_service_client.ts
  src/v4/job_service_client.ts
  src/v4/tenant_service_client.ts
  src/v4beta1/application_service_client.ts
  src/v4beta1/company_service_client.ts
  src/v4beta1/completion_client.ts
  src/v4beta1/event_service_client.ts
  src/v4beta1/job_service_client.ts
  src/v4beta1/profile_service_client.ts
  src/v4beta1/tenant_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: jobs, automerge, cla: yes

#274 fix(browser): check for fetch on window
  protos/protos.json
  src/v4/company_service_client.ts
  src/v4/completion_client.ts
  src/v4/event_service_client.ts
  src/v4/job_service_client.ts
  src/v4/tenant_service_client.ts
  src/v4beta1/application_service_client.ts
  src/v4beta1/company_service_client.ts
  src/v4beta1/completion_client.ts
  src/v4beta1/event_service_client.ts
  src/v4beta1/job_service_client.ts
  src/v4beta1/profile_service_client.ts
  src/v4beta1/tenant_service_client.ts
  synth.metadata
Labels: api: jobs, cla: yes, context: partial

#276 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: full
